'use client';
import Link from'next/link';import{useEffect,useState}from'react';import{api,apiConfigured,endpoints,getToken}from'@/lib/api';import{tools}from'@/lib/tools';
export default function AppDashboard(){const[status,setStatus]=useState<any>(null),[sources,setSources]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!apiConfigured())return;try{const[s,src]=await Promise.all([api(endpoints.status),api(endpoints.sources)]);setStatus(s);setSources(src.sources||[]);if(getToken())setProjects(await api(endpoints.projects))}catch(e:any){setError(e.message||'API unavailable')}})()},[]);
 const providers=status?.providers||{};return <main className="workspace"><div className="eyebrow">PROPERTY DEVELOPMENT, AUGMENTED</div><h1>Project intelligence workspace.</h1><p className="lede">SITE → BUILD → PROVE. Live data, AI-assisted analysis, project controls and evidence — with source provenance and human review gates.</p>
 <section className="toolWorkbench"><div className={`status ${apiConfigured()&&!error?'live':'demo'}`}>{apiConfigured()&&!error?'INDEPENDENT API CONNECTED':'API NOT CONNECTED'}{error?` · ${error}`:''}</div><h2>Data & AI status</h2><div className="grid">{Object.entries(providers).map(([k,v])=><article className="card" key={k}><small>{String(k).replaceAll('_',' ').toUpperCase()}</small><h3>{v?'Configured':'Not configured'}</h3><p>{v?'Available to the independent backend.':'The platform will show an honest unavailable state rather than fabricated data.'}</p></article>)}</div></section>
 <section><div className="sectionHead"><div><div className="eyebrow">PROJECTS</div><h2>{projects.length?`${projects.length} project${projects.length===1?'':'s'}`:'Create your first project'}</h2></div><Link className="button" href="/app/projects">Manage projects</Link></div>{projects.length>0&&<div className="grid">{projects.slice(0,6).map(p=><Link key={p.id} className="card" href={`/app/site-intelligence?project=${p.id}`} onClick={()=>localStorage.setItem('pda_project',String(p.id))}><span className="stage site">PROJECT</span><h3>{p.name}</h3><p>{p.address||p.postcode||'No location set'}</p></Link>)}</div>}</section>
 <section className="panel"><div className="sectionHead"><div><div className="eyebrow">TOOLS</div><h2>Intelligence and controls</h2></div></div><div className="grid">{tools.map(t=><Link key={t.slug} className="card" href={`/app/${t.slug}`}><span className={`stage ${t.stage.toLowerCase()}`}>{t.stage}</span><h3>{t.title}</h3><p>{t.short}</p></Link>)}</div></section>
 <section><h2>Authoritative-source layer</h2><div className="grid">{sources.map((s:any)=><article className="card" key={s.url}><small>{s.name}</small><p>{s.caveat}</p><a href={s.url} target="_blank" rel="noreferrer">Open source ↗</a></article>)}</div></section></main>}
