'use client';
import{useState}from'react';
import{api,endpoints}from'@/lib/api';

type Mode='appraisal'|'residual'|'finance'|'build'|'maxbid'|'profit'|'cil'|'planning';
const labels:Record<Mode,string>={appraisal:'Development appraisal',residual:'Residual land value',finance:'Development finance',build:'Manual build cost',maxbid:'Maximum land bid',profit:'Profit target',cil:'CIL estimate',planning:'Planning fee — England'};
const money=(v:any)=>Number.isFinite(Number(v))?`£${Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}`:String(v??'—');
const num=(v:string)=>{const n=Number(v);return Number.isFinite(n)?n:0};
export default function CalculatorSuiteClient(){
 const[mode,setMode]=useState<Mode>('appraisal'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[v,setV]=useState<Record<string,string>>({holding_months:'12',annual_rate_pct:'10',months:'12',target_profit_pct_gdv:'20',target_profit_pct_cost:'0',preliminaries_pct:'0',contingency_pct:'7.5',vat_pct:'0',index_multiplier:'1',relief_or_exemption_pct:'0',dwellings:'1',additional_dwellings:'0',category:'householder_single'});
 const set=(k:string,x:string)=>setV(s=>({...s,[k]:x}));
 const fields=(items:string[])=> <div className="formGrid">{items.map(k=><label key={k}>{k.replaceAll('_',' ')}<input inputMode="decimal" value={v[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}</div>;
 async function run(){setBusy(true);setError('');setResult(null);try{let path:string;let body:any;
  if(mode==='appraisal'){path=endpoints.appraisal;body={acquisition:num(v.acquisition),transaction_costs:num(v.transaction_costs),construction:num(v.construction),professional_fees:num(v.professional_fees),finance:num(v.finance),contingency:num(v.contingency),other_costs:num(v.other_costs),gdv:num(v.gdv),rental_income_annual:num(v.rental_income_annual),holding_months:num(v.holding_months)||12}}
  else if(mode==='residual'){path=endpoints.residual;body={gdv:num(v.gdv),construction:num(v.construction),professional_fees:num(v.professional_fees),finance:num(v.finance),contingency:num(v.contingency),other_costs:num(v.other_costs),target_profit:num(v.target_profit),transaction_costs:num(v.transaction_costs)}}
  else if(mode==='finance'){path=endpoints.finance;body={principal:num(v.principal),annual_rate_pct:num(v.annual_rate_pct),months:num(v.months),compounding:v.compounding||'simple'}}
  else if(mode==='build'){path=endpoints.manualBuildCost;body={area_sqft:num(v.area_sqft),cost_per_sqft:num(v.cost_per_sqft),preliminaries_pct:num(v.preliminaries_pct),contingency_pct:num(v.contingency_pct),vat_pct:num(v.vat_pct)}}
  else if(mode==='maxbid'){path=endpoints.maxLandBid;body={gdv:num(v.gdv),construction:num(v.construction),professional_fees:num(v.professional_fees),finance:num(v.finance),contingency:num(v.contingency),planning_obligations:num(v.planning_obligations),sales_and_marketing:num(v.sales_and_marketing),other_costs:num(v.other_costs),acquisition_costs_excluding_land:num(v.acquisition_costs_excluding_land),target_profit_pct_gdv:num(v.target_profit_pct_gdv)}}
  else if(mode==='profit'){path=endpoints.profitTarget;body={gdv:num(v.gdv),total_cost_excluding_profit:num(v.total_cost_excluding_profit),target_profit_pct_gdv:num(v.target_profit_pct_gdv),target_profit_pct_cost:num(v.target_profit_pct_cost)}}
  else if(mode==='cil'){path=endpoints.cilEstimate;body={chargeable_area_sqm:num(v.chargeable_area_sqm),local_rate_per_sqm:num(v.local_rate_per_sqm),index_multiplier:num(v.index_multiplier)||1,relief_or_exemption_pct:num(v.relief_or_exemption_pct),existing_lawful_floor_area_credit_sqm:num(v.existing_lawful_floor_area_credit_sqm)}}
  else {path=endpoints.planningFee;body={category:v.category||'householder_single',dwellings:Math.max(0,Math.round(num(v.dwellings))),additional_dwellings:Math.max(0,Math.round(num(v.additional_dwellings))),gross_new_floor_area_sqm:num(v.gross_new_floor_area_sqm)}}
  setResult(await api(path,{method:'POST',body:JSON.stringify(body)}));
 }catch(e:any){setError(e.message||'Calculation failed')}finally{setBusy(false)}}
 return <div className="toolWorkbench"><section className="panel"><div className="eyebrow">DETERMINISTIC CALCULATORS</div><h2>Numbers with visible assumptions.</h2><p>Use the calculators for arithmetic, then move the result into Development Intelligence HQ when live policy, market, title and technical evidence need to challenge the assumptions.</p><div className="sourceChips">{(Object.keys(labels)as Mode[]).map(m=><button key={m} className={`mini ${mode===m?'active':''}`} onClick={()=>{setMode(m);setResult(null);setError('')}}>{labels[m]}</button>)}</div></section>
 <section className="panel"><h2>{labels[mode]}</h2>
 {mode==='appraisal'&&fields(['acquisition','transaction_costs','construction','professional_fees','finance','contingency','other_costs','gdv','rental_income_annual','holding_months'])}
 {mode==='residual'&&fields(['gdv','construction','professional_fees','finance','contingency','other_costs','target_profit','transaction_costs'])}
 {mode==='finance'&&<><div className="formGrid">{fields(['principal','annual_rate_pct','months'])}<label>compounding<select value={v.compounding||'simple'} onChange={e=>set('compounding',e.target.value)}><option value="simple">Simple</option><option value="monthly">Monthly</option></select></label></div></>}
 {mode==='build'&&fields(['area_sqft','cost_per_sqft','preliminaries_pct','contingency_pct','vat_pct'])}
 {mode==='maxbid'&&fields(['gdv','construction','professional_fees','finance','contingency','planning_obligations','sales_and_marketing','other_costs','acquisition_costs_excluding_land','target_profit_pct_gdv'])}
 {mode==='profit'&&fields(['gdv','total_cost_excluding_profit','target_profit_pct_gdv','target_profit_pct_cost'])}
 {mode==='cil'&&<><p className="muted">Enter the verified local CIL rate. The calculator deliberately does not guess a local charging schedule.</p>{fields(['chargeable_area_sqm','existing_lawful_floor_area_credit_sqm','local_rate_per_sqm','index_multiplier','relief_or_exemption_pct'])}</>}
 {mode==='planning'&&<><label>application category<select value={v.category||'householder_single'} onChange={e=>set('category',e.target.value)}><option value="householder_single">Householder — single dwelling</option><option value="householder_multiple">Householder — 2+ dwellings</option><option value="dwelling_full">Full application — new dwellings</option><option value="change_use_to_dwellings">Change of use to dwellings</option><option value="other_change_of_use">Other material change of use</option><option value="other_operations_floor_area">Other building operations by new floor area</option><option value="prior_approval_householder">Prior approval — householder</option><option value="prior_approval_class_ma">Prior approval — Class MA to dwellings</option><option value="discharge_householder">Discharge condition — householder</option><option value="discharge_other">Discharge condition — other</option><option value="non_material_householder">Non-material amendment — householder</option><option value="non_material_other">Non-material amendment — other</option></select></label>{fields(['dwellings','additional_dwellings','gross_new_floor_area_sqm'])}<p className="muted">Selected common England categories from the statutory fee schedule effective 1 April 2026. Verify the current fee at submission.</p></>}
 <button className="button premium" disabled={busy} onClick={run}>{busy?'Calculating…':'Calculate'}</button>{error&&<div className="error">{error}</div>}</section>
 {result&&<section className="result"><div className="resultHead"><h3>Calculation result</h3><button className="mini" onClick={()=>navigator.clipboard.writeText(JSON.stringify(result,null,2))}>Copy</button></div><div className="grid">{Object.entries(result).filter(([,x])=>['number','string','boolean'].includes(typeof x)).slice(0,12).map(([k,x])=><article className="card" key={k}><small>{k.replaceAll('_',' ').toUpperCase()}</small><h3>{typeof x==='number'&&/(cost|profit|fee|cil|price|value|gdv|interest|total|headroom|bid)/.test(k)?money(x):String(x)}</h3></article>)}</div><pre>{JSON.stringify(result,null,2)}</pre></section>}
 <div className="humanGate"><b>Commercial evidence gate</b><p>These calculators are deterministic arithmetic, not valuations, tax advice, planning decisions or QS cost plans. For live sites, carry the output into Development Intelligence HQ so current policy, title, market, technical and professional evidence can challenge the inputs.</p></div></div>;
}
