/* eslint-disable @next/next/no-img-element */
'use client';
import{useEffect,useMemo,useState}from'react';
import{api,absoluteApi,endpoints}from'@/lib/api';

function initialProject(value:string){if(value)return value;if(typeof window==='undefined')return'';return localStorage.getItem('pda_project')||''}
function number(v:string){const n=Number(v);return Number.isFinite(n)?n:0}
function money(v:any){const n=Number(v);return Number.isFinite(n)?`£${Math.round(n).toLocaleString()}`:'Not established'}
function tileXY(lat:number,lon:number,z:number){const n=2**z;const x=Math.floor((lon+180)/360*n);const r=lat*Math.PI/180;const y=Math.floor((1-Math.asinh(Math.tan(r))/Math.PI)/2*n);return{x,y}}
function OSMap({lat,lon}:{lat:number;lon:number}){const z=18;const c=tileXY(lat,lon,z);const cells=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)cells.push({x:c.x+dx,y:c.y+dy});return <div style={{position:'relative',maxWidth:768}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',overflow:'hidden',borderRadius:12}}>{cells.map((t,i)=><img key={i} alt="Ordnance Survey map tile" src={absoluteApi(`/api/v1/maps/os/${z}/${t.x}/${t.y}.png?layer=Light_3857`)} style={{width:'100%',display:'block'}}/>)}</div><div aria-label="Approximate site centre" title="Approximate site centre" style={{position:'absolute',left:'50%',top:'50%',transform:'translate(-50%,-50%)',width:18,height:18,borderRadius:99,border:'4px solid currentColor'}}/></div>}
function Panel({title,value}:{title:string;value:any}){if(!value)return null;return <section className="result"><div className="resultHead"><h3>{title}</h3><button className="mini" onClick={()=>navigator.clipboard.writeText(JSON.stringify(value,null,2))}>Copy JSON</button></div><pre>{JSON.stringify(value,null,2)}</pre></section>}
function AgentSummary({value}:{value:any}){const report=value?.specialist_analysis?.report||value?.report;if(!report)return null;return <section className="result"><h3>Specialist analysis</h3><p>{report.executive_summary}</p>{Array.isArray(report.findings)&&<div className="grid">{report.findings.slice(0,9).map((x:any,i:number)=><article className="card" key={x.id||i}><small>{String(x.classification||'finding').replaceAll('_',' ').toUpperCase()} · {String(x.materiality||'').toUpperCase()}</small><h3>{x.claim}</h3><p>{x.verification_action}</p></article>)}</div>}</section>}
export default function DevelopmentIntelligenceClient({initialProjectId=''}:{initialProjectId?:string}){
 const[projectId]=useState(()=>initialProject(initialProjectId));const[postcode,setPostcode]=useState(''),[address,setAddress]=useState(''),[proposal,setProposal]=useState(''),[domain,setDomain]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[data,setData]=useState<Record<string,any>>({});
 const[purchase,setPurchase]=useState(''),[preSqft,setPreSqft]=useState(''),[postSqft,setPostSqft]=useState(''),[siteArea,setSiteArea]=useState(''),[budget,setBudget]=useState(''),[maxPrice,setMaxPrice]=useState('');
 useEffect(()=>{Promise.all([api<any>(endpoints.sourceCatalogue),api<any>(endpoints.landRegistration),api<any>(endpoints.regulations),api<any>(endpoints.sourceHealth)]).then(([sources,land,regulations,health])=>setData(x=>({...x,sources,land,regulations,health}))).catch(()=>{})},[]);
 const geo=data.dossier?.geospatial||data.geo;const lat=Number(geo?.geocode?.latitude),lon=Number(geo?.geocode?.longitude),easting=Number(geo?.geocode?.eastings),northing=Number(geo?.geocode?.northings);const google=geo?.maps?.google;const topo=geo?.maps?.topography;const osReady=Boolean(geo?.maps?.os_tile_template&&Number.isFinite(lat)&&Number.isFinite(lon));const landMapReady=Number.isFinite(easting)&&Number.isFinite(northing);
 const sourceSummary=useMemo(()=>data.sources?.sources||[],[data.sources]);
 async function run(key:string,path:string,body:any){setBusy(key);setError('');try{const r=await api<any>(path,{method:'POST',body:JSON.stringify(body),timeoutMs:240000});setData(x=>({...x,[key]:r}));return r}catch(e:any){setError(e.message||'Request failed')}finally{setBusy('')}}
 function base(){return{postcode:postcode.trim(),address:address.trim(),proposal:proposal.trim(),local_authority_domain:domain.trim(),project_id:projectId?Number(projectId):null}}
 async function dossier(){if(!postcode.trim())return setError('Enter a postcode.');await run('dossier',endpoints.dossier,{...base(),depth:'enriched',include_live_policy:true})}
 async function saveDossier(){if(!projectId||!data.dossier)return setError('Select a project first.');setBusy('save');setError('');try{await api(`/api/v1/projects/${projectId}/registers`,{method:'POST',body:JSON.stringify({kind:'evidence',title:`Development Intelligence dossier · ${address||postcode}`,status:'Captured',data:{captured_at:new Date().toISOString(),dossier:data.dossier}})});setData(x=>({...x,saved:true}))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <div className="toolWorkbench">
  <div className="status live">ONE ADDRESS → SITE → POLICY → DESIGN → VALUE → BUILD → PROVE</div>
  <div className="formGrid"><label>Postcode<input value={postcode} onChange={e=>setPostcode(e.target.value)} placeholder="e.g. RG45 7XX"/></label><label>Address / site<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Full address or site description"/></label><label>Development idea<textarea value={proposal} onChange={e=>setProposal(e.target.value)} placeholder="e.g. retain commercial ground floor, add two storeys and 4 flats"/></label><label>Local authority domain (optional — auto-discovered if blank)<input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="e.g. bracknell-forest.gov.uk"/></label></div>
  <div className="actions"><button className="button" disabled={!!busy} onClick={dossier}>{busy==='dossier'?'Building live dossier…':'Build full site dossier'}</button><button className="button ghost" disabled={!!busy||!postcode} onClick={()=>run('geo',endpoints.geoContext,{postcode,address,radius_m:350})}>Map room only</button><button className="button ghost" disabled={!!busy||!data.dossier||!projectId} onClick={saveDossier}>{data.saved?'Saved to Evidence Room':'Save dossier as evidence'}</button></div>{error&&<div className="error">{error}</div>}

  <section><div className="sectionHead"><div><div className="eyebrow">SOURCE FABRIC</div><h2>Live intelligence coverage</h2></div></div><div className="grid">{sourceSummary.map((x:any)=><article className="card" key={x.id}><small>{String(x.kind).toUpperCase()} · {x.access}</small><h3>{x.name}</h3><p>{x.use}</p><div className={`status ${x.configured?'live':'demo'}`}>{x.configured?'READY':'LICENCE / KEY NEEDED'}</div></article>)}</div></section>

  {geo&&<section><div className="sectionHead"><div><div className="eyebrow">GEOSPATIAL + TITLE ROOM</div><h2>OS + HMLR freehold screen + satellite + Street View + LiDAR</h2></div></div><div className="grid"><article className="card"><small>POSITION</small><h3>{geo.os_address?.matches?.[0]?.address||geo.geocode?.postcode}</h3><p>UPRN: {geo.os_address?.matches?.[0]?.uprn||'Not established'}<br/>BNG: {geo.geocode?.eastings||'—'}, {geo.geocode?.northings||'—'}<br/>Authority: {geo.geocode?.admin_district||'—'}</p></article><article className="card"><small>LAND REGISTRATION</small><h3>Registration evidence gate</h3><p>INSPIRE screens indicative registered freehold extents. A spatial gap is never labelled unregistered until a Search of the Index Map confirms it.</p></article></div>{osReady&&<><h3>Ordnance Survey</h3><OSMap lat={lat} lon={lon}/></>}{landMapReady&&<div className="grid"><article><h3>HM Land Registry INSPIRE freehold screen</h3><img alt="HM Land Registry INSPIRE registered freehold index polygons" src={absoluteApi(`/api/v1/maps/hmlr-inspire.png?easting=${easting}&northing=${northing}&radius_m=350`)} style={{width:'100%',borderRadius:12}}/><p className="muted">Indicative registered freehold index polygons only. No polygon does not prove land is unregistered.</p></article><article className="card"><small>UNREGISTERED LAND WORKFLOW</small><h3>INSPIRE → title evidence → SIM</h3><p>Potential gaps are escalated to official Search of the Index Map confirmation; they are not automatically called unregistered land.</p></article></div>}{google?.configured&&<div className="grid"><article><h3>Google satellite</h3><iframe title="Google satellite map" src={google.map_embed_url} loading="lazy" style={{border:0,width:'100%',height:420}} allowFullScreen/></article><article><h3>Google Street View</h3><iframe title="Google Street View" src={google.streetview_embed_url} loading="lazy" style={{border:0,width:'100%',height:420}} allowFullScreen/></article></div>}{topo?.available&&<div className="grid"><article><h3>EA LiDAR terrain model</h3><img alt="Environment Agency LiDAR digital terrain model" src={absoluteApi(topo.dtm_image)} style={{width:'100%',borderRadius:12}}/></article><article><h3>EA LiDAR surface model</h3><img alt="Environment Agency LiDAR digital surface model" src={absoluteApi(topo.dsm_image)} style={{width:'100%',borderRadius:12}}/></article></div>}<div className="humanGate"><b>Boundary and levels gate</b><p>OS, HMLR index mapping, LiDAR and postcode/address layers are evidence layers. Legal title extent and material design levels still require the appropriate title documents and measured survey.</p></div></section>}

  <section className="panel"><div className="eyebrow">PLANNING PROSPECTS ENGINE</div><h2>What is getting through here — and why?</h2><p>Retrieves current policy, materially similar local applications and appeal evidence, then forces the specialist agent to explain the differences instead of manufacturing an approval percentage.</p><div className="actions"><button className="button" disabled={!!busy||!postcode||!proposal} onClick={()=>run('prospects',endpoints.planningProspects,{...base(),max_age_days:3650})}>{busy==='prospects'?'Comparing decisions…':'Analyse planning prospects + appeals'}</button><button className="button ghost" disabled={!!busy||!postcode} onClick={()=>run('policyPack',endpoints.policyPack,base())}>{busy==='policyPack'?'Retrieving policy stack…':'Build complete local policy pack'}</button></div>{data.prospects?.measured_local_sample&&<div className="grid"><article className="card"><small>COMPARABLE SAMPLE</small><h3>{data.prospects.measured_local_sample.decided_sample_size||0} clearly decided matches</h3><p>Historical positive share: {data.prospects.measured_local_sample.historical_positive_share_pct??'Not enough comparable evidence'}.</p></article><article className="card"><small>RULE</small><h3>Precedent is evidence, not a guarantee</h3><p>{data.prospects.measured_local_sample.rule}</p></article></div>}<AgentSummary value={data.prospects}/></section>

  <section className="panel"><div className="eyebrow">ARCHITECTURE + SITE DEVELOPMENT</div><h2>Three evidence-led scheme directions</h2><div className="formGrid"><label>Site area m²<input inputMode="decimal" value={siteArea} onChange={e=>setSiteArea(e.target.value)}/></label><label>Indicative budget £<input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)}/></label></div><button className="button" disabled={!!busy||!postcode||!proposal} onClick={()=>run('concepts',endpoints.developmentConcepts,{postcode,address,development_goal:proposal,site_area_sqm:number(siteArea)||null,budget_gbp:number(budget)||null,project_id:projectId?Number(projectId):null})}>{busy==='concepts'?'Developing options…':'Generate planning-led / balanced / upside concepts'}</button><AgentSummary value={data.concepts}/></section>

  <section className="panel"><div className="eyebrow">VALUE + COST + DEAL ENGINE</div><h2>Evidence before price opinion</h2><div className="formGrid"><label>Purchase / asking price £<input inputMode="decimal" value={purchase} onChange={e=>setPurchase(e.target.value)}/></label><label>Existing area ft²<input inputMode="decimal" value={preSqft} onChange={e=>setPreSqft(e.target.value)}/></label><label>Proposed area ft²<input inputMode="decimal" value={postSqft} onChange={e=>setPostSqft(e.target.value)}/></label><label>Deal scan max price £<input inputMode="decimal" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/></label></div><div className="actions"><button className="button" disabled={!!busy||!postcode||!postSqft} onClick={()=>run('siteValue',endpoints.siteValue,{postcode,purchase_price:number(purchase),pre_development_sqft:number(preSqft)||1,post_development_sqft:number(postSqft),finish_quality:'medium',project_type:'new_build'})}>{busy==='siteValue'?'Building value stack…':'Build cost + GDV + residual site value'}</button><button className="button ghost" disabled={!!busy||!postcode} onClick={()=>run('deals',endpoints.marketDealScan,{postcode,max_price:number(maxPrice)||null,strategy:proposal||'development opportunity',lists:['unmodernised-properties','reduced-properties','slow-to-sell-properties'],radius_miles:20,results:20,page:1})}>{busy==='deals'?'Scanning licensed market…':'Scan development deals'}</button></div>{data.siteValue?.derived_metrics&&<div className="grid"><article className="card"><small>RESIDUAL SITE VALUE</small><h3>{money(data.siteValue.derived_metrics.residual_site_value_before_unmodelled_tax_abnormals_and_risk)}</h3><p>Before unmodelled tax, CIL/S106, abnormal/site-specific costs and risk.</p></article><article className="card"><small>EVIDENCE-BACKED GDV</small><h3>{money(data.siteValue.derived_metrics.evidence_backed_gdv)}</h3><p>Build cost: {money(data.siteValue.derived_metrics.build_cost)} · target profit: {money(data.siteValue.derived_metrics.target_profit_used)}</p></article></div>}{data.deals?.candidates&&<div className="grid">{data.deals.candidates.slice(0,12).map((x:any,i:number)=><article className="card" key={x.id||i}><small>{String(x.triage_signal||'review').replaceAll('_',' ').toUpperCase()}</small><h3>{x.address||x.postcode}</h3><p>Ask: {x.asking_price?`£${Number(x.asking_price).toLocaleString()}`:'—'}<br/>Local HMLR median: {x.hmlr_local_median_sold_price?`£${Number(x.hmlr_local_median_sold_price).toLocaleString()}`:'Not established'}<br/>Ask vs local median: {x.ask_vs_hmlr_median_pct??'—'}%</p></article>)}</div>}<AgentSummary value={data.deals}/></section>

  <section className="panel"><div className="eyebrow">SUBMISSION + TECHNICAL COST PLAN</div><h2>What needs commissioning, what it costs, and what can be drafted now</h2><div className="actions"><button className="button" disabled={!!busy||!postcode||!proposal} onClick={()=>run('fees',endpoints.feePlan,base())}>{busy==='fees'?'Researching current fees…':'Build planning + consultant fee plan'}</button><button className="button ghost" disabled={!!busy||!postcode||!proposal} onClick={()=>run('applicationPack',endpoints.applicationPack,{...base(),include_market_evidence:true})}>{busy==='applicationPack'?'Producing application pack…':'Generate planning application preparation pack'}</button></div><p>Published statutory/provider fees are sourced. Bespoke consultant costs stay <b>PRICE NOT ESTABLISHED</b> until a current quote exists. Professional reports remain explicitly marked for competent authorship/sign-off.</p></section>

  <section><div className="sectionHead"><div><div className="eyebrow">TECHNICAL COORDINATION</div><h2>Planning + Building Regulations + structure + transport + environment</h2></div></div><div className="grid">{(data.regulations?.building_regulations||[]).map((x:any)=><article className="card" key={x.code}><small>APPROVED DOCUMENT {x.code}</small><h3>{x.topic}</h3><p>Lead: {x.lead}</p></article>)}</div></section>

  <Panel title="Full dossier / source bundle" value={data.dossier}/><Panel title="Local policy pack" value={data.policyPack}/><Panel title="Planning prospects raw evidence" value={data.prospects}/><Panel title="Architecture concepts raw output" value={data.concepts}/><Panel title="Site value evidence" value={data.siteValue}/><Panel title="Application preparation pack" value={data.applicationPack}/><Panel title="Fee and submission evidence" value={data.fees}/><Panel title="Source health" value={data.health}/>
  <div className="humanGate"><b>Professional evidence gate</b><p>This system can assemble and challenge the evidence faster; it does not turn a postcode, map, historic permission, portal listing or AI inference into a legal title, valuation, planning permission, structural design, Building Regulations approval or investment recommendation.</p></div>
 </div>
}
