'use client';
import{useEffect,useMemo,useState}from'react';import{api,apiConfigured,apiDownload,API_BASE,endpoints}from'@/lib/api';import type{Tool}from'@/lib/tools';

type Source={name?:string;url?:string;retrieved_at?:string;caveat?:string};
const registerKinds:Record<string,string>={'risk-register':'risk','variation-tracker':'variation','decision-log':'decision','evidence-room':'evidence'};
const modes:Record<string,string>={'planning-intelligence':'planning-evidence','quote-comparator':'procurement','risk-register':'project-controls','variation-tracker':'project-controls','decision-log':'project-controls','consultant-brief':'report-writer','weekly-reporting':'report-writer','evidence-room':'project-controls','ai-assistant':'report-writer'};
function sourcesOf(value:any,out:Source[]=[]):Source[]{if(!value||typeof value!=='object')return out;if(typeof value.url==='string'&&(value.name||value.caveat||value.retrieved_at))out.push(value);for(const v of Object.values(value))sourcesOf(v,out);return out}
function n(v:string){const x=Number(v);return Number.isFinite(x)?x:0}
function initialProject(initialProjectId:string){if(initialProjectId)return initialProjectId;if(typeof window==='undefined')return'';return localStorage.getItem('pda_project')||''}
export default function ToolClient({tool,initialProjectId=''}:{tool:Tool;initialProjectId?:string}){
 const[postcode,setPostcode]=useState(''),[address,setAddress]=useState(''),[prompt,setPrompt]=useState(''),[file,setFile]=useState<File|null>(null),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[format,setFormat]=useState('pdf'),[projectId]=useState(()=>initialProject(initialProjectId)),[compounding,setCompounding]=useState('simple');
 const[calc,setCalc]=useState<Record<string,string>>({acquisition:'',transaction_costs:'',construction:'',professional_fees:'',finance:'',contingency:'',other_costs:'',gdv:'',rental_income_annual:'',holding_months:'12',target_profit:'',principal:'',annual_rate_pct:'',months:'12'});
 const live=apiConfigured();useEffect(()=>{if(initialProjectId&&typeof window!=='undefined')localStorage.setItem('pda_project',initialProjectId)},[initialProjectId]);
 const foundSources=useMemo(()=>Array.from(new Map(sourcesOf(result).map(s=>[s.url||s.name,s])).values()),[result]);
 function setField(k:string,v:string){setCalc(x=>({...x,[k]:v}))}
 async function project(){if(!projectId)throw new Error('Select or create a project first.');return api(`/api/v1/projects/${projectId}`)}
 async function registerRun(){if(!projectId)throw new Error('Select or create a project first.');const kind=registerKinds[tool.slug];const path=`/api/v1/projects/${projectId}/registers/${kind}`;if(!prompt.trim())return api(path);const data=JSON.parse(prompt);let status=data.status||'Open';if(kind==='variation'&&!data.approval&&!data.approval_evidence&&!data.approved)status='Approval not evidenced';await api(`/api/v1/projects/${projectId}/registers`,{method:'POST',body:JSON.stringify({kind,title:data.title||data.description||tool.title,status,data})});return api(path)}
 async function run(){setBusy(true);setError('');setMessage('');try{
   if(!live)throw new Error('Live API is not configured. Set NEXT_PUBLIC_API_BASE_URL; this workspace does not fabricate demo results.');
   if(tool.slug==='site-intelligence')setResult(await api(endpoints.site,{method:'POST',body:JSON.stringify({postcode,address,radius_km:2,include_epc:true})}));
   else if(tool.slug==='development-appraisal')setResult(await api(endpoints.appraisal,{method:'POST',body:JSON.stringify({acquisition:n(calc.acquisition),transaction_costs:n(calc.transaction_costs),construction:n(calc.construction),professional_fees:n(calc.professional_fees),finance:n(calc.finance),contingency:n(calc.contingency),other_costs:n(calc.other_costs),gdv:n(calc.gdv),rental_income_annual:n(calc.rental_income_annual),holding_months:n(calc.holding_months)})}));
   else if(tool.slug==='residual-land-value')setResult(await api(endpoints.residual,{method:'POST',body:JSON.stringify({gdv:n(calc.gdv),construction:n(calc.construction),professional_fees:n(calc.professional_fees),finance:n(calc.finance),contingency:n(calc.contingency),other_costs:n(calc.other_costs),target_profit:n(calc.target_profit),transaction_costs:n(calc.transaction_costs)})}));
   else if(tool.slug==='finance-calculator')setResult(await api(endpoints.finance,{method:'POST',body:JSON.stringify({principal:n(calc.principal),annual_rate_pct:n(calc.annual_rate_pct),months:n(calc.months),compounding})}));
   else if(tool.slug==='deep-research')setResult(await api(endpoints.deepResearch,{method:'POST',body:JSON.stringify({topic:prompt,postcode,address}),timeoutMs:90000}));
   else if(tool.slug==='seo-studio')setResult(await api(endpoints.seo,{method:'POST',body:JSON.stringify({seeds:(prompt||'AI property developers UK').split(',').map(x=>x.trim()).filter(Boolean),site_url:address}),timeoutMs:90000}));
   else if(tool.slug==='quote-comparator'){const quotes=JSON.parse(prompt||'[]');setResult(await api(endpoints.quotes,{method:'POST',body:JSON.stringify({quotes,context:`${address} ${postcode}`}),timeoutMs:90000}))}
   else if(tool.slug==='document-intelligence'&&file){const fd=new FormData();fd.append('file',file);if(projectId)fd.append('project_id',projectId);const uploaded:any=await api(endpoints.upload,{method:'POST',body:fd});const analysis=await api(endpoints.analyse,{method:'POST',body:JSON.stringify({mode:'report-writer',question:prompt||'Interrogate this document. Extract established facts, assumptions, dates, limitations, contradictions, missing evidence and verification actions.',context:{filename:uploaded.filename,sha256:uploaded.sha256,material:uploaded.text}}),timeoutMs:90000});setResult({...uploaded,analysis})}
   else if(registerKinds[tool.slug])setResult(await registerRun());
   else if(tool.slug==='weekly-reporting'){const p=await project();setResult(await api(endpoints.analyse,{method:'POST',body:JSON.stringify({mode:'report-writer',question:prompt||'Produce the weekly management report: progress, decisions required, information outstanding, top risks, variations/cost issues, programme issues and next priorities. Use only the project records; missing information = not established.',context:{project:p}}),timeoutMs:90000}))}
   else if(tool.slug==='consultant-brief'){const p=projectId?await project():null;setResult(await api(endpoints.analyse,{method:'POST',body:JSON.stringify({mode:'report-writer',question:prompt||'Create a precise consultant brief: decision/problem, established facts, documents, exact questions, required inputs/deliverables, assumptions not to make, programme, dependencies and exclusions.',context:{project:p,address,postcode}}),timeoutMs:90000}))}
   else if(tool.slug==='report-studio'){const data=prompt.trim()?JSON.parse(prompt):projectId?await project():{};await apiDownload(endpoints.report,{method:'POST',body:JSON.stringify({title:data.title||'Property Development, Augmented Report',format,data})},`property-augmented-report.${format}`);setResult({downloaded:true,format,note:'Report generated by the independent API.'})}
   else if(tool.slug==='products-consultancy')setResult(await api(endpoints.products));
   else if(tool.slug==='calculators')setResult({message:'Choose Development Appraisal, Residual Land Value or Development Finance from the workspace navigation for a structured calculator.'});
   else setResult(await api(endpoints.analyse,{method:'POST',body:JSON.stringify({mode:modes[tool.slug]||'report-writer',text:prompt,question:prompt||`Run ${tool.title}`,context:{postcode,address,project_id:projectId||null}}),timeoutMs:90000}));
 }catch(e:any){setError(e.message||'Request failed')}finally{setBusy(false)}}
 async function trends(){setBusy(true);setError('');try{setResult(await api(endpoints.trends,{method:'POST',body:JSON.stringify({geo:'GB',limit:30})}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function measured(){setBusy(true);setError('');try{setResult(await api(endpoints.measuredKeywords,{method:'POST',body:JSON.stringify({keywords:(prompt||'AI property developers UK').split(',').map(x=>x.trim()).filter(Boolean),database:'uk'})}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function searchConsole(){setBusy(true);setError('');try{setResult(await api(endpoints.searchConsole,{method:'POST',body:JSON.stringify({site_url:address})}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveEvidence(){if(!projectId||!result)return;setBusy(true);setError('');try{await api(`/api/v1/projects/${projectId}/registers`,{method:'POST',body:JSON.stringify({kind:'evidence',title:`${tool.title} result`,status:'Captured',data:{tool:tool.slug,captured_at:new Date().toISOString(),result}})});setMessage('Saved to the project Evidence Room.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const calculator=['development-appraisal','residual-land-value','finance-calculator'].includes(tool.slug);const money=['acquisition','transaction_costs','construction','professional_fees','finance','contingency','other_costs','gdv','rental_income_annual','target_profit'];
 return <div className="toolWorkbench"><div className={`status ${live?'live':'demo'}`}>{live?'LIVE INDEPENDENT API':'API NOT CONFIGURED'} · {live?API_BASE:'set NEXT_PUBLIC_API_BASE_URL'}</div>{projectId&&<p className="muted">Active project ID: {projectId}</p>}
 {tool.slug==='site-intelligence'&&<div className="formGrid"><label>Postcode<input value={postcode} onChange={e=>setPostcode(e.target.value)} placeholder="e.g. RG45 7XX"/></label><label>Address / project<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Optional address detail"/></label></div>}
 {calculator&&<><div className="formGrid">{tool.slug==='finance-calculator'?<>{['principal','annual_rate_pct','months'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input inputMode="decimal" value={calc[k]} onChange={e=>setField(k,e.target.value)}/></label>)}<label>Compounding<select value={compounding} onChange={e=>setCompounding(e.target.value)}><option value="simple">Simple</option><option value="monthly">Monthly</option></select></label></>:money.filter(k=>tool.slug==='residual-land-value'?k!=='acquisition'&&k!=='rental_income_annual':k!=='target_profit').map(k=><label key={k}>{k.replaceAll('_',' ')}<input inputMode="decimal" value={calc[k]} onChange={e=>setField(k,e.target.value)}/></label>)}</div></>}
 {tool.slug==='document-intelligence'&&<label>Project document<input type="file" accept=".pdf,.docx,.xlsx,.xlsm,.csv,.txt,.md,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}
 {!calculator&&tool.slug!=='site-intelligence'&&tool.slug!=='products-consultancy'&&tool.slug!=='calculators'&&<label>{registerKinds[tool.slug]?'Optional JSON record (leave blank to list existing records)':'Question / structured input'}<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={tool.slug==='quote-comparator'?'[{"contractor":"A","total":10000,"scope":"..."}]':tool.slug==='report-studio'?'{"title":"Weekly Project Report","summary":"..."}':registerKinds[tool.slug]?'{"title":"Risk / variation / decision","owner":"...","status":"Open"}':'Describe exactly what you want analysed…'}/></label>}
 {tool.slug==='seo-studio'&&<label>Search Console property URL (optional)<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="sc-domain:example.com or URL-prefix property"/></label>}
 {tool.slug==='report-studio'&&<label>Output format<select value={format} onChange={e=>setFormat(e.target.value)}><option>pdf</option><option>docx</option><option>xlsx</option><option>csv</option><option>json</option></select></label>}
 <div className="actions"><button className="button" onClick={run} disabled={busy}>{busy?'Working…':registerKinds[tool.slug]&&!prompt.trim()?'Load records':tool.slug==='report-studio'?'Generate download':'Run'}</button>{tool.slug==='seo-studio'&&<><button className="button ghost" onClick={trends} disabled={busy}>UK Trending now</button><button className="button ghost" onClick={measured} disabled={busy}>Measured keyword data</button><button className="button ghost" onClick={searchConsole} disabled={busy}>Search Console</button></>}{projectId&&result&&!registerKinds[tool.slug]&&<button className="button ghost" onClick={saveEvidence} disabled={busy}>Save to Evidence Room</button>}</div>{message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}
 {foundSources.length>0&&<section className="result"><h3>Sources & freshness</h3><div className="grid">{foundSources.map((s,i)=><article className="card" key={(s.url||s.name||'source')+i}><small>{s.name||'Source'}</small>{s.retrieved_at&&<p>Retrieved: {s.retrieved_at}</p>}{s.caveat&&<p>{s.caveat}</p>}{s.url&&<a href={s.url} target="_blank" rel="noreferrer">Open authoritative source ↗</a>}</article>)}</div></section>}
 {result&&<section className="result"><div className="resultHead"><h3>Result</h3><button className="mini" onClick={()=>navigator.clipboard.writeText(JSON.stringify(result,null,2))}>Copy JSON</button></div><pre>{JSON.stringify(result,null,2)}</pre></section>}
 <div className="humanGate"><b>Human review gate</b><p>AI output is working material until reviewed. Verify source, date, revision and material numbers. If evidence is missing, record <strong>not established</strong>. Discussion is not approval. Statutory, legal, technical, financial and safety judgements remain with the appropriate qualified person or authority.</p></div></div>
}
