import{toolMap,type Tool}from'./tools';
export type SeoPage={slug:string;tool:string;title:string;description:string;intent:string;uses:string[];limits:string[]};
export const seoPages:SeoPage[]=[
{slug:'planning-application-ai',tool:'planning-intelligence',title:'Planning Application AI for UK Developers',description:'Use AI to organise planning evidence, chronologies, contradictions and information gaps without pretending software can decide an application.',intent:'planning application AI',uses:['planning documents supplied by the user','source-backed policy discovery','evidence matrices and chronology'],limits:['does not predict approval','does not replace a planning professional or decision-maker']},
{slug:'planning-constraints-checker',tool:'site-intelligence',title:'Planning Constraints Checker for UK Development Sites',description:'Research government planning datasets, flood information, sold-price evidence and policy discovery around a UK postcode.',intent:'planning constraints checker',uses:['Planning Data beta datasets','Environment Agency flood-monitoring data','HM Land Registry Price Paid Data','GOV.UK discovery'],limits:['coverage varies by authority/dataset','postcode location is not surveyed site geometry','sold prices are not valuations']},
{slug:'postcode-development-feasibility',tool:'development-intelligence',title:'Postcode Development Feasibility & Planning Intelligence UK',description:'Start with a UK postcode and build a live site, policy, planning, mapping, title, market and commercial evidence dossier before professional spend accelerates.',intent:'postcode property development feasibility',uses:['postcodes and address resolution','live local/national policy','planning/appeal evidence','market/cost/site-value evidence when configured'],limits:['postcode is not legal title or measured survey','does not guarantee permission, value or buildability']},
{slug:'property-development-appraisal-calculator',tool:'development-appraisal',title:'Property Development Appraisal Calculator UK',description:'Calculate total development cost, profit, margin on cost, margin on GDV and ROI from transparent inputs.',intent:'property development appraisal calculator',uses:['user-entered acquisition, cost, finance and GDV assumptions'],limits:['not a valuation','not a tax calculation or QS cost plan','outputs are only as reliable as the inputs']},
{slug:'residual-land-value-calculator',tool:'residual-land-value',title:'Residual Land Value Calculator UK',description:'Calculate a residual land amount after development costs and target profit using explicit assumptions.',intent:'residual land value calculator',uses:['GDV and user-entered cost/profit assumptions'],limits:['not a professional valuation','does not account for every tax, finance or abnormal-cost scenario unless entered']},
{slug:'maximum-land-bid-calculator',tool:'calculators',title:'Maximum Land Bid Calculator for UK Property Development',description:'Calculate the theoretical maximum amount available for land after development costs and a target developer return, with explicit risk warnings.',intent:'maximum land bid calculator',uses:['user-entered GDV, build, finance, professional, planning and other costs'],limits:['not a valuation or acquisition recommendation','unpriced tax, title, abnormal and planning risks require separate allowance']},
{slug:'planning-fee-calculator-england-2026',tool:'calculators',title:'Planning Application Fee Calculator England 2026',description:'Estimate selected common England planning application fees using the statutory fee schedule effective 1 April 2026, with the schedule date and source shown.',intent:'planning fee calculator 2026',uses:['selected common application categories','MHCLG 1 April 2026 statutory fee schedule'],limits:['verify the current fee at submission','does not include every category, portal charge, local discretionary service or future fee change']},
{slug:'cil-calculator-development',tool:'calculators',title:'CIL Calculator for UK Development Feasibility',description:'Estimate Community Infrastructure Levy from a verified local rate, chargeable area, index multiplier and user-entered floorspace credit or relief.',intent:'CIL calculator development',uses:['user-supplied local CIL rate and verified area assumptions'],limits:['does not invent a local charging rate','not a liability notice or legal/planning advice']},
{slug:'biodiversity-net-gain-development-feasibility',tool:'development-intelligence',title:'Biodiversity Net Gain Feasibility for UK Development Sites',description:'Identify current BNG policy triggers and evidence gaps as part of postcode-first development feasibility without inventing ecology results or costs.',intent:'biodiversity net gain development feasibility',uses:['current national guidance','live local policy research','site evidence and professional ecology inputs when available'],limits:['does not calculate habitat units without the required evidence','does not replace an ecologist or Biodiversity Gain Plan']},
{slug:'construction-quote-comparison',tool:'quote-comparator',title:'AI Construction Quote Comparison Tool',description:'Normalise contractor quotations, identify exclusions and provisional sums and create clarification questions.',intent:'construction quote comparison',uses:['contractor quotations supplied by the user'],limits:['does not appoint a contractor','does not certify value or contractual entitlement']},
{slug:'construction-risk-register',tool:'risk-register',title:'Construction Risk Register Tool',description:'Create and maintain cause-event-consequence risks with ownership, mitigation and status.',intent:'construction risk register',uses:['project records and user-entered risk information'],limits:['risk scoring remains management judgement','does not replace technical or safety assessment']},
{slug:'construction-variation-tracker',tool:'variation-tracker',title:'Construction Variation Tracker',description:'Track scope change, evidence, cost and approval status without converting discussion into approval.',intent:'construction variation tracker',uses:['project records and user-entered change information'],limits:['does not determine contractual entitlement','approval is not inferred']},
{slug:'construction-decision-log',tool:'decision-log',title:'Construction Decision Log & Evidence Trail',description:'Preserve what was decided, when, by whom and against which evidence.',intent:'construction decision log',uses:['verified project records and evidence references'],limits:['does not manufacture authority or agreement','source records should be retained']},
{slug:'construction-weekly-report',tool:'weekly-reporting',title:'AI Construction Weekly Report Generator',description:'Draft a management report from maintained project records rather than rebuilding project memory every week.',intent:'construction weekly report AI',uses:['verified project registers, actions, risks and progress information'],limits:['AI narrative must be reviewed','does not create facts missing from the registers']},
{slug:'document-intelligence',tool:'document-intelligence',title:'AI Document Intelligence for Property & Construction',description:'Extract, hash and interrogate PDF, DOCX, XLSX, CSV, TXT and JSON project files.',intent:'construction document intelligence',uses:['documents uploaded by the authorised user'],limits:['extraction can be incomplete','professional conclusions require specialist review']},
{slug:'ai-for-property-developers',tool:'ai-assistant',title:'AI for Property Developers UK — Evidence-Led Workflows',description:'Use specialist AI modes across site research, planning evidence, procurement, project controls and reporting.',intent:'AI for property developers UK',uses:['live sources, user documents and project context when configured'],limits:['AI augments judgement','no guaranteed planning, cost or investment outcome']}
];
export const seoPageMap=Object.fromEntries(seoPages.map(x=>[x.slug,x])) as Record<string,SeoPage>;
export function resolveSeoPage(slug:string):{tool:Tool;page:SeoPage|undefined}|null{const page=seoPageMap[slug];const tool=toolMap[page?.tool||slug];return tool?{tool,page}:null}
