export type Tool={slug:string;stage:'SITE'|'BUILD'|'PROVE'|'SYSTEM';title:string;short:string;keywords:string[];publicTitle:string;meta:string};
export const tools:Tool[]=[
{slug:'agent-studio',stage:'SYSTEM',title:'Specialist Agent Studio',short:'Run evidence-first specialist agents individually or as a red-teamed committee, with every material claim classified and reviewable.',keywords:['property development AI agents','construction AI agents','AI evidence analysis'],publicTitle:'Specialist AI Agents for Property Development & Construction',meta:'Use specialist UK property and construction agents with structured evidence, source traceability and human review.'},
{slug:'site-intelligence',stage:'SITE',title:'Site Intelligence',short:'Pull planning constraints, sold-price evidence, flood data, policy discovery and source freshness into one evidence-led view.',keywords:['planning constraints checker','UK property data analysis','site feasibility AI'],publicTitle:'AI Site Intelligence for UK Property Development',meta:'Research a UK development opportunity with source-backed planning, property, flood and policy data.'},
{slug:'planning-intelligence',stage:'SITE',title:'Planning Intelligence',short:'Build evidence matrices, policy maps, refusal deconstruction, chronologies, contradictions and adviser questions.',keywords:['planning application AI','planning evidence matrix','planning policy analysis'],publicTitle:'AI Planning Intelligence & Evidence Matrix',meta:'Analyse planning documents and evidence gaps without replacing professional judgement.'},
{slug:'policy-library',stage:'SITE',title:'Policy & Standards Library',short:'Search a curated current national source index and run official-domain policy research while keeping local-policy gaps explicit.',keywords:['UK planning policy search','NPPF 2026','building regulations guidance'],publicTitle:'UK Planning Policy & Building Standards Intelligence',meta:'Research current UK planning policy and building guidance from official sources, with local-policy limitations made explicit.'},
{slug:'development-appraisal',stage:'SITE',title:'Development Appraisal',short:'Model total development cost, profit, margins and ROI with explicit assumptions.',keywords:['property development appraisal calculator','development profit calculator'],publicTitle:'Property Development Appraisal Calculator UK',meta:'Calculate development costs, profit, margins and ROI with transparent assumptions.'},
{slug:'scenario-lab',stage:'SITE',title:'Scenario Lab',short:'Stress-test GDV and construction-cost assumptions across a transparent 49-scenario sensitivity matrix without invented probabilities.',keywords:['property development sensitivity analysis','development scenario calculator','GDV sensitivity'],publicTitle:'Property Development Scenario & Sensitivity Lab',meta:'Stress-test development profit against GDV and construction cost movements with deterministic transparent calculations.'},
{slug:'residual-land-value',stage:'SITE',title:'Residual Land Value',short:'Calculate the residual amount available for land after project costs and target profit.',keywords:['residual land value calculator','property development land value'],publicTitle:'Residual Land Value Calculator UK',meta:'Calculate residual land value from GDV, project costs and target profit with explicit assumptions.'},
{slug:'finance-calculator',stage:'SITE',title:'Development Finance',short:'Model simple or monthly-compounded development finance interest.',keywords:['property development finance calculator','development loan interest calculator'],publicTitle:'Property Development Finance Calculator UK',meta:'Illustrative development finance interest calculations with transparent assumptions.'},
{slug:'quote-comparator',stage:'BUILD',title:'Quote Comparator',short:'Normalise contractor quotations and generate clarification questions.',keywords:['construction quote comparison','AI construction software UK'],publicTitle:'AI Construction Quote Comparison Tool',meta:'Compare construction quotations like-for-like and identify scope gaps.'},
{slug:'risk-register',stage:'BUILD',title:'Risk Register',short:'Structure cause, event, consequence, probability, impact, mitigation, trigger, owner and status.',keywords:['construction risk register','AI project management construction'],publicTitle:'Construction Risk Register',meta:'Maintain a structured construction risk register with transparent scoring and ownership.'},
{slug:'variation-tracker',stage:'BUILD',title:'Variation Tracker',short:'Track cost, programme, evidence and approval status; never infer approval.',keywords:['variation tracker construction','construction change control'],publicTitle:'Construction Variation Tracker',meta:'Control construction variations, evidence, cost status and approvals.'},
{slug:'decision-log',stage:'PROVE',title:'Decision Log',short:'Preserve what was decided, by whom, on what evidence and what happens next.',keywords:['construction decision log','project evidence management'],publicTitle:'Construction Decision Log & Evidence Trail',meta:'Create a reliable decision record for property and construction projects.'},
{slug:'document-intelligence',stage:'PROVE',title:'Document Intelligence',short:'Store and audit private PDF, DOCX, XLSX, CSV, TXT and JSON evidence with ownership, retention and SHA-256 provenance.',keywords:['AI document analysis construction','construction document intelligence'],publicTitle:'Secure AI Construction Document Intelligence',meta:'Store and analyse project documents with evidence provenance, retention controls and human verification.'},
{slug:'consultant-brief',stage:'SITE',title:'Consultant Brief Builder',short:'Turn fragmented project facts into a precise professional brief.',keywords:['consultant brief property development','planning consultant brief'],publicTitle:'Property Consultant Brief Builder',meta:'Create structured briefs for planning, transport, acoustic, engineering, QS and design consultants.'},
{slug:'weekly-reporting',stage:'BUILD',title:'Weekly Reporting',short:'Generate management narratives from maintained project registers.',keywords:['construction weekly report AI','construction project reporting'],publicTitle:'AI Construction Weekly Reporting',meta:'Turn verified project information into concise weekly management reports.'},
{slug:'evidence-room',stage:'PROVE',title:'Evidence Review Room',short:'Review structured claims, verification actions, contradictions and evidence health; export a fingerprinted project Decision Pack.',keywords:['construction evidence management','property project audit trail'],publicTitle:'Property & Construction Evidence Review Room',meta:'Review AI-extracted claims and create an auditable evidence trail across the development lifecycle.'},
{slug:'audit-trail',stage:'PROVE',title:'Audit Trail',short:'Inspect authenticated state-changing API activity without storing request bodies or secrets.',keywords:['construction audit trail','AI governance audit log'],publicTitle:'Property Development AI Audit Trail',meta:'Review authenticated change activity across the independent property development platform.'},
{slug:'report-studio',stage:'SYSTEM',title:'Report Studio',short:'Export project data as PDF, DOCX, XLSX, CSV or JSON.',keywords:['construction report generator','property development report'],publicTitle:'Property Development AI Report Studio',meta:'Generate reviewable property and construction reports in multiple formats.'},
{slug:'deep-research',stage:'SYSTEM',title:'Deep Research Agent',short:'Combine authoritative datasets, live web search and AI synthesis with complete consulted-source metadata and uncertainty flags.',keywords:['property development research AI','deep research property'],publicTitle:'AI Property Development Deep Research Agent',meta:'Research UK property, planning or construction questions with live web search and source-backed evidence.'},
{slug:'ai-assistant',stage:'SYSTEM',title:'AI Project Assistant',short:'Specialist Site, Planning Evidence, Procurement, Project Controls, Report Writer and SEO modes.',keywords:['property development AI assistant','construction AI assistant'],publicTitle:'AI Assistant for Property Development & Construction',meta:'A context-aware AI assistant for evidence-led UK property and construction workflows.'},
{slug:'calculators',stage:'SYSTEM',title:'Calculators Hub',short:'Appraisal, scenario, residual land value and finance tools with transparent inputs.',keywords:['property development calculator UK','construction finance calculator'],publicTitle:'Property Development Calculators UK',meta:'Transparent calculators for development appraisal, scenario testing, finance and residual land value.'},
{slug:'seo-studio',stage:'SYSTEM',title:'SEO & Authority Studio',short:'Map keyword research, Google Trends, Search Console and measured provider data without inventing metrics.',keywords:['property development SEO','construction SEO AI'],publicTitle:'Property & Construction SEO Intelligence',meta:'Build a source-aware SEO and authority strategy for property, construction and PropTech brands.'},
{slug:'products-consultancy',stage:'SYSTEM',title:'Products & Consultancy',short:'View digital products, entitlement state and consultancy/lead workflows.',keywords:['property development AI toolkit','AI construction consultancy UK'],publicTitle:'Property Development AI Toolkit & Consultancy',meta:'Access Property Development, Augmented digital products and consultancy workflows.'}
];
export const toolMap=Object.fromEntries(tools.map(t=>[t.slug,t])) as Record<string,Tool>;
