export type Tool={slug:string;stage:'SITE'|'BUILD'|'PROVE'|'SYSTEM';title:string;short:string;keywords:string[];publicTitle:string;meta:string};
export const tools:Tool[]=[
{slug:'site-intelligence',stage:'SITE',title:'Site Intelligence',short:'Pull planning constraints, sold-price evidence, flood data, policy discovery and source freshness into one evidence-led view.',keywords:['planning constraints checker','UK property data analysis','site feasibility AI'],publicTitle:'AI Site Intelligence for UK Property Development',meta:'Research a UK development opportunity with source-backed planning, property, flood and policy data.'},
{slug:'planning-intelligence',stage:'SITE',title:'Planning Intelligence',short:'Build evidence matrices, policy maps, refusal deconstruction, chronologies, contradictions and adviser questions.',keywords:['planning application AI','planning evidence matrix','planning policy analysis'],publicTitle:'AI Planning Intelligence & Evidence Matrix',meta:'Analyse planning documents and evidence gaps without replacing professional judgement.'},
{slug:'development-appraisal',stage:'SITE',title:'Development Appraisal',short:'Model total development cost, profit, margins, ROI and residual land value with explicit assumptions.',keywords:['property development appraisal calculator','residual land value calculator'],publicTitle:'Property Development Appraisal Calculator UK',meta:'Calculate development costs, profit, margins and residual land value with transparent assumptions.'},
{slug:'quote-comparator',stage:'BUILD',title:'Quote Comparator',short:'Normalise contractor quotations and generate clarification questions.',keywords:['construction quote comparison','AI construction software UK'],publicTitle:'AI Construction Quote Comparison Tool',meta:'Compare construction quotations like-for-like and identify scope gaps.'},
{slug:'risk-register',stage:'BUILD',title:'Risk Register',short:'Structure cause, event, consequence, probability, impact, mitigation, trigger, owner and status.',keywords:['construction risk register','AI project management construction'],publicTitle:'Construction Risk Register',meta:'Maintain a structured construction risk register with transparent scoring and ownership.'},
{slug:'variation-tracker',stage:'BUILD',title:'Variation Tracker',short:'Track cost, programme, evidence and approval status; never infer approval.',keywords:['variation tracker construction','construction change control'],publicTitle:'Construction Variation Tracker',meta:'Control construction variations, evidence, cost status and approvals.'},
{slug:'decision-log',stage:'PROVE',title:'Decision Log',short:'Preserve what was decided, by whom, on what evidence and what happens next.',keywords:['construction decision log','project evidence management'],publicTitle:'Construction Decision Log & Evidence Trail',meta:'Create a reliable decision record for property and construction projects.'},
{slug:'document-intelligence',stage:'PROVE',title:'Document Intelligence',short:'Upload and interrogate PDF, DOCX, XLSX and CSV documents with source identifiers.',keywords:['AI document analysis construction','construction document intelligence'],publicTitle:'AI Construction Document Intelligence',meta:'Analyse and compare project documents with human verification.'},
{slug:'consultant-brief',stage:'SITE',title:'Consultant Brief Builder',short:'Turn fragmented project facts into a precise professional brief.',keywords:['consultant brief property development','planning consultant brief'],publicTitle:'Property Consultant Brief Builder',meta:'Create structured briefs for planning, transport, acoustic, engineering, QS and design consultants.'},
{slug:'weekly-reporting',stage:'BUILD',title:'Weekly Reporting',short:'Generate management narratives from maintained project registers.',keywords:['construction weekly report AI','construction project reporting'],publicTitle:'AI Construction Weekly Reporting',meta:'Turn verified project information into concise weekly management reports.'},
{slug:'evidence-room',stage:'PROVE',title:'Evidence Room',short:'Maintain chronology, evidence, documents, decisions and handover readiness.',keywords:['construction evidence management','property project audit trail'],publicTitle:'Property & Construction Evidence Room',meta:'Create an auditable evidence trail across the development lifecycle.'},
{slug:'report-studio',stage:'SYSTEM',title:'Report Studio',short:'Export project data as PDF, DOCX, XLSX, CSV or JSON.',keywords:['construction report generator','property development report'],publicTitle:'Property Development AI Report Studio',meta:'Generate reviewable property and construction reports in multiple formats.'},
{slug:'deep-research',stage:'SYSTEM',title:'Deep Research Agent',short:'Combine live source discovery, site data and AI synthesis with uncertainty flags.',keywords:['property development research AI','deep research property'],publicTitle:'AI Property Development Deep Research Agent',meta:'Research UK property, planning or construction questions with source-backed evidence.'},
{slug:'ai-assistant',stage:'SYSTEM',title:'AI Project Assistant',short:'Specialist Site, Planning Evidence, Procurement, Project Controls and Report Writer modes.',keywords:['property development AI assistant','construction AI assistant'],publicTitle:'AI Assistant for Property Development & Construction',meta:'A context-aware AI assistant for evidence-led UK property and construction workflows.'},
{slug:'calculators',stage:'SYSTEM',title:'Calculators Hub',short:'Appraisal, residual land value, finance, contingency and scenario tools.',keywords:['property development calculator UK','construction finance calculator'],publicTitle:'Property Development Calculators UK',meta:'Transparent calculators for development appraisal, finance and residual land value.'},
{slug:'seo-studio',stage:'SYSTEM',title:'SEO & Authority Studio',short:'Map keyword research, trend inputs and content opportunities without inventing metrics.',keywords:['property development SEO','construction SEO AI'],publicTitle:'Property & Construction SEO Intelligence',meta:'Build a source-aware SEO and authority strategy for property, construction and PropTech brands.'}
];
export const toolMap=Object.fromEntries(tools.map(t=>[t.slug,t]));
